# Generated by Django 2.0 on 2021-12-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_opcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textoPregunta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaBinaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.BooleanField(choices=[(1, 'Sí'), (0, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_preferencia', models.PositiveIntegerField(blank=True, null=True)),
                ('opcionRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.OpcionRespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='VotacionBinaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VotacionPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='respuestabinaria',
            name='votacionBinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotacionBinaria'),
        ),
        migrations.AddField(
            model_name='preguntapreferencia',
            name='votacionPreferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotacionPreferencia'),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='preguntaPreferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.PreguntaPreferencia'),
        ),
    ]
