# Generated by Django 2.0 on 2022-01-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY')], default='IDENTITY', max_length=10),
        ),
    ]
